### ISSUE TITLE
From header to support TEL URI

### ISSUE THREAD

**Issue by games130** [negbie/sipparser#2]
@negbie, wondering if you can add the support to parse TEL URI from the FROM header.

Sample of the FROM header with TEL URI:
```
From: tel:+4512345678;tag=752520ac91292bae839ce09f3fa382aa
From: <tel:180012345678;user=phone>;tag=sbc09033drebier-CC-3
```

I found that currently if it is TEL URI, the from_user is store as:
```
+4512345678;tag=f905c6f5b474e36defdd56559823ad86
180012345678;user=phone
```

I am unable to find where in the RFC that say TEL URI can be use in the FROM header.
RFC 3261 BNF section defines Request-URI as follows:
	Request-URI    =  SIP-URI / SIPS-URI / absoluteURI

**Comment by negbie** [comment]
Hi,
since dialogic is doing this it must be in any rfc ;)
https://www.dialogic.com/webhelp/IMG2020/2.3.0/WebHelp/te_uri.htm

Anyway good catch! Give me some minutes to implement it.

**Comment by negbie** [comment]
This commit should fix it
https://github.com/negbie/sipparser/commit/df2ab418faa9f1f0a58ae74a7e898098d8d44ac8

**Comment by games130** [comment]
thanks for the fix, will test it and post back the result.

**Comment by games130** [comment]
@negbie it is working well. From headers are parsing well with TEL URI
