### ISSUE TITLE
Partially upercase Call-id header format

### ISSUE THREAD

**Issue by dvillaume** [negbie/sipparser#3]
Hi,

I got a "WARN Could not find a valid Call-ID in packet" with this callid :

Call-id: aa3942fcc10150e19d07cff68f5273b6\r\n

I guess it disapeared it could be related to: https://github.com/negbie/sipparser/commit/3f355fd28235b04e95003d8719595d007f19e50d

May you have a look please ? (i can sent you full message in private if needed)

David

**Comment by negbie** [comment]
Done

**Comment by dvillaume** [comment]
Thanks.

Le ven. 13 juil. 2018 à 14:32, Eugen Biegler <notifications@github.com> a
écrit :
